// memories.js - All memory data separated from the main HTML
const memories = [
    {
        number: -194,
        location: "Curzon Hall",
        lat: 23.727361,
        lng: 90.401444,
        date: "February 18, 2019",
        images: ["images/-194.jpg"],
        note: "The journey didn't start here, when you randomly wanted to take a selfie",
    },
    {
        number: 1,
        location: "Crimson Cup",
        lat: 23.738824, 
        lng: 90.378759,
        date: "August 31, 2019",
        images: ["images/0.jpg"],
        note: "Everyone canceled, except us. And that's where the journey began. We sat in crimson cup for an hour after the movie, because you had to pick Urbi from college. We talked about entropy and random stuff. I took a random photo and sent mehrin. Mehrin said Me Crimson cup and you were two things she never thought would collide.",
        journeyNote: "194 days passed since this selfie. On one random day, you decided to ask me to go on a hangout with you guys. And on an eventual hangout all of us decided to go watch Spider Man: Far from home."
    },
    {
        number: 27,
        location: "Pizza Burg",
        lat: 23.747459,
        lng: 90.370319,
        date: "September 26, 2019",
        images: ["images/27.jpg"],
        note: "Everyone went to pizza burg",
    },
    {
        number: 32,
        location: "Curzon Hall",
        lat: 23.727361,
        lng: 90.401444,
        date: "Oct 1, 2019",
        images: ["images/32.jpg"],
        note: "Me photographs everyone in the rain",
    },
    {
        number: 50,
        location: "TSC",
        lat: 23.731748, 
        lng: 90.395574,
        date: "Oct 19, 2019",
        images: ["images/50.jpg"],
        note: "First time I celebrated your birthday. Gave you a earphone, probably the first gift I ever gave you.",
    },
    {
        number: 60,
        location: "Second Cup",
        lat: 23.747448, 
        lng: 90.369940,
        date: "Oct 30, 2019",
        images: ["images/60.jpg"],
        note: "Random hangouts at 2nd cup begin.",
    },
    {
        number: 65,
        location: "Samsunnahar Hall",
        lat: 23.731278, 
        lng: 90.395061,
        date: "Nov 4, 2019",
        images: ["images/65.jpg"],
        note: "Having street food infront of Samsunnahar hall.",
    },
    {
        number: 67,
        location: "Curzon Hall",
        lat: 23.727361,
        lng: 90.401444,
        date: "Nov 7, 2019",
        images: ["images/67.jpg"],
        note: "The day you learned I know a few bangla songs XD.",
    },
    {
        number: 74,
        location: "Second Cup",
        lat: 23.747448, 
        lng: 90.369940,
        date: "Oct 19, 2019",
        images: ["images/74.jpg"],
        note: "The day you lost your earphone.",
    },
    {
        number: 86,
        location: "Curzon Hall",
        lat: 23.727361,
        lng: 90.401444,
        date: "Nov 24, 2019",
        images: ["images/85.jpg", "images/85-2.jpg"],
        note: "3rd year class party. And here begins our usual 2nd cup hangouts",
    },
    {
        number: 85,
        location: "Curzon Hall",
        lat: 23.727361,
        lng: 90.401444,
        date: "Dec 1, 2019",
        images: ["images/92.jpg"],
        note: "Nini came to hangout.",
    },
    {           
        number: 99,
        location: "Storm in a cup",
        lat: 23.738992,
        lng: 90.383206,
        date: "Dec 7, 2019",
        images: ["images/99.jpg"],
        note: "The first of our 50's hangouts even though it wasn't technically 100. We went to Aarong after probably power systems exam, the one I failed XD. The we went to storm in a cup, and had food.",
    },
    {           
        number: 114,
        location: "Karnafuli Garden City",
        lat: 23.738992,
        lng: 90.383206,
        date: "Dec 22, 2019",
        images: ["images/114.jpg"],
        note: "The day we celebrated Tapo's birthday and went to Karnafuli Garden City. You took a photo of me in the exact place where I took a photo in my childhood.",
    },
    {           
        number: 150,
        location: "Crimson Cup",
        lat: 23.752880, 
        lng: 90.369478,
        date: "Jan 28, 2020",
        images: ["images/150.jpg"],
        note: "We went to DU Economics dept, met bushra, went to Crimson Cup. Later on went to Chefs Table.",
    },
        {
        number: 166,
        location: "Curzon Hall",
        lat: 23.728361,
        lng: 90.401444,
        date: "February 12, 2020",
        images: ["images/166.jpg"],
        note: "The start of spring.",
    },

        {
        number: 170,
        location: "Horshochash 2020",
        lat: 24.093294,
        lng: 90.314772,
        date: "February 16, 2020",
        images: ["images/170.jpg"],
        note: "The first picnic I ever went to. We sang all the way there and back. ",
    },

        {
        number: 178,
        location: "TSC",
        lat: 23.732074,
        lng: 90.395789,
        date: "February 24, 2020",
        images: ["images/178.jpg"],
        note: "The last Nobinboron. The first time I went to back stage and edited some time stamps or something. ",
    },

        {
        number: 184,
        location: "Second Cup",
        lat: 23.747448,
        lng: 90.36994,
        date: "March 1, 2020",
        images: ["images/184.jpg"],
        note: "The day you found a leaf and decided to draw on it",
    },

        {
        number: 194,
        location: "Shena Kunja",
        lat: 23.803477,
        lng: 90.398559,
        date: "March 11, 2020",
        images: ["images/194.jpg"],
        note: "The day we went to Bushra's brother's reception. This day is exactly the same number of days away from Day 1. As Day 1 was from the day of our first selfie. ",
    },

    {
        number: 200,
        location: "Coffee World",
        lat: 23.753206,
        lng: 90.369446,
        date: "March 16, 2020",
        images: ["images/200.jpg"],
        note: "The last hangout before the world went to COVID lockdown. ",
        
    },

        {
        number: 504,
        location: "BSH",
        lat: 23.776501,
        lng: 90.362738,
        date: "January 15, 2021",
        images: ["images/504.jpg"],
        note: "Probably the first time we met after the lockdown.",
        journeyNote: "So many things happened in this timeline. So many late night calls, so many valorant maches, so many anime we watched. "
    },

        {
        number: 506,
        location: "IDB",
        lat: 23.77851,
        lng: 90.379869,
        date: "January 17, 2021",
        images: ["images/506.jpg"],
        note: "We went to IDB, We got Saidul's mouse.",
    },

    {
        number: 518,
        location: "Second Cup",
        lat: 23.747448,
        lng: 90.36994,
        date: "January 29, 2021",
        images: ["images/518.jpg"],
        note: "Probably the first time we went to Second Cup after the Lockdown",
    },

        {
        number: 539,
        location: "Your house",
        lat: 23.71901,
        lng: 90.423325,
        date: "February 19, 2021",
        images: ["images/539.jpg"],
        note: "Here is to our many hangouts at your house and your rooftop during COVID.",
    },

        {
        number: 560,
        location: "My house",
        lat: 23.768436,
        lng: 90.363496,
        date: "March 12, 2021",
        images: ["images/560.jpg"],
        note: "The day I gave you Kakashi.",
    },

];